### ISSUE TITLE
Is it is 7.0+ or iOS 8.0+?

### ISSUE THREAD

**Issue by ShadeApps** [MoZhouqi/KMPlaceholderTextView#1]
During pod installation I get this message:

`The platform of the target `Pods` (iOS 7.0) is not compatible with `KMPlaceholderTextView (0.1.1)` which has a minimum requirement of iOS 8.0.`

Yet, in the requirements for the control you say it's 7.0+

What am I doing wrong?

**Comment by MoZhouqi** [comment]
Dynamic frameworks are unsupported on iOS 7, so you can add the `KMPlaceholderTextView.swift` source file directly into your application project.
