### ISSUE TITLE
Override `init(frame: CGRect, textContainer: NSTextContainer?)` to be public?

### ISSUE THREAD

**Issue by mbalex99** [MoZhouqi/KMPlaceholderTextView#10]
Is there a reason

The init method isn't public? 

`init(frame: CGRect, textContainer: NSTextContainer?)`

I'd like to subclass this.

**Comment by MoZhouqi** [comment]
Fixed in e8e0257542c75fb825048c6de140d3ddef93f2c6. Thanks for reporting @mbalex99.
