### ISSUE TITLE
IB Designables error

### ISSUE THREAD

**Issue by misuqian** [MoZhouqi/KMPlaceholderTextView#11]
error: IB Designables: Failed to render instance of KMPlaceholderTextView: Rendering the view took longer than 200 ms. Your drawing code may suffer from slow performance.

how can i figure that error?

**Comment by MoZhouqi** [comment]
Hi, could you give me a demo thus I can find the problem more accurately.

**Comment by zuo305** [comment]
same issue.

**Comment by BhavinBhadani** [comment]
Its not an issue by KMPlaceholderTextView..Its an issue of IB Designables .It may be bug in XCode, more ofter this error comes in IB Designables.but it resolves automatically.So don't worry about it.
