### ISSUE TITLE
Install manually

### ISSUE THREAD

**Issue by aldolazuardi** [MoZhouqi/KMPlaceholderTextView#12]
how to install KMPlaceholderTextView manually without cocoapods?

**Comment by MoZhouqi** [comment]
Just drag the `KMPlaceholderTextView.swift` file into your project.

**Comment by aldolazuardi** [comment]
i already did that, but it shows this error message
<img width="793" alt="screen shot 2016-01-27 at 10 06 59 am" src="https://cloud.githubusercontent.com/assets/9720223/12602682/d62195ac-c4dd-11e5-91bd-abaa93cc123c.png">

**Comment by MoZhouqi** [comment]
It's so strange, UITextView hasn't the `placeholder` property. I just tried it and there was no complier error.
