### ISSUE TITLE
Has ambiguous scrollable content height

### ISSUE THREAD

**Issue by paulz** [MoZhouqi/KMPlaceholderTextView#16]
Thank you for useful pod!

We have an issue using it in a storyboard. When adding a height constraint to the it Storyboard shows the warning: `Has ambiguous scrollable content height`.

Is there a workaround for that? Or way to fix it?

After investigation and StackOverflow research we think it's because IBDesignable KMPlaceholderTextView has placeholder subview, which UITextView UIScrollView probably takes as content and cause ambiguity.

**Comment by paulz** [comment]
Here is an example of the issue:

https://github.com/MoZhouqi/KMPlaceholderTextView/compare/master...paulz:master

in my fork: https://github.com/paulz/KMPlaceholderTextView

**Comment by MoZhouqi** [comment]
Fixed in d670bb34adb98f6f4e328c5e29ed8eafd84838f6. Thanks for the feedback!
