### ISSUE TITLE
Swift 2.2 warnings

### ISSUE THREAD

**Issue by paulz** [MoZhouqi/KMPlaceholderTextView#17]
Thank you for the awesome Pod!

We just migrated to swift 2.2 and we liked how KMPlaceholderTextView had no warnings before. Now we are getting a few, see below. Would it be possible to have a release without warnings? Thank you!

▸ Compiling KMPlaceholderTextView.swift

⚠️ /Pods/KMPlaceholderTextView/KMPlaceholderTextView/KMPlaceholderTextView.swift:90:23: use of string literal for Objective-C selectors is deprecated; use '#selector' instead

            selector: "textDidChange",
                      ^~~~~~~~~~~~~~~

▸ Compiling KMPlaceholderTextView.swift

⚠️  /Pods/KMPlaceholderTextView/KMPlaceholderTextView/KMPlaceholderTextView.swift:90:23: use of string literal for Objective-C selectors is deprecated; use '#selector' instead

            selector: "textDidChange",
                      ^~~~~~~~~~~~~~~

**Comment by MoZhouqi** [comment]
Fixed in release 1.2.0. Thanks for your feedback.
