### ISSUE TITLE
IB Designables Failure

### ISSUE THREAD

**Issue by sinanulkuatam** [MoZhouqi/KMPlaceholderTextView#18]
Hello!

I'm getting this issue with the latest version...

file:///Users/sulkuatam/src/app/app-ios/Base.lproj/Main.storyboard: error: IB Designables: Failed to update auto layout status: The bundle “$(PRODUCT_NAME)” couldn’t be loaded because its executable couldn’t be located.

Not sure what the issue is... thanks in advance for any help!

<img width="259" alt="screen shot 2016-05-31 at 11 36 52 am" src="https://cloud.githubusercontent.com/assets/1269987/15680508/f9618b78-2723-11e6-8e86-f694dd946995.png">

**Comment by MoZhouqi** [comment]
Hi, have you tried it in the example?

**Comment by sinanulkuatam** [comment]
Strange, must be an error on my end!  I'll take a closer look...

**Comment by MoZhouqi** [comment]
Similar to https://github.com/hsousa/HCSStarRatingView/issues/25. But this library is written in Swift, so you should have specified `use_frameworks!`.
