### ISSUE TITLE
Feature request: Separate fonts of placeholder and text?

### ISSUE THREAD

**Issue by karadis** [MoZhouqi/KMPlaceholderTextView#20]
Other than color, it's very common to have a bolded or italic font for the placeholder, which is different from the regular text the user input.
Can you add an option to set the placeholder font?
thanks!

**Comment by MoZhouqi** [comment]
Hi, the feature has been added in the latest release.

**Comment by karadis** [comment]
Sorry, i was with 1.2.0. I see it now, thank you.

**Comment by MoZhouqi** [comment]
It is not your fault, I just released the version 1.2.1 one hour ago.
