### ISSUE TITLE
Rendering Performance

### ISSUE THREAD

**Issue by Nykho** [MoZhouqi/KMPlaceholderTextView#22]
Hi
The KMPlaceholderTextView won't give access to the UILabel used, so it's really difficult to setup the backgroundColor. Why do we care about it if it's transparent?. One of the slowest operations is rendering. In my case I'm using a lot of instances of KMPlaceholderTextView so if you use “Color Blended Layers" in the iPhone Simulator, you will see a lot of red areas.

It would be really useful to have access to the background color of the UILabel - through a method- or the UILabel. Right now it's marked as private.

**Comment by MoZhouqi** [comment]
`placeholderLabel` is public in release 1.2.2.

**Comment by Nykho** [comment]
Cool! and thanks :)

**Comment by MoZhouqi** [comment]
My pleasure!
