### ISSUE TITLE
Can't see placeholder after set in Storyboard

### ISSUE THREAD

**Issue by Nik20112** [MoZhouqi/KMPlaceholderTextView#23]
Hi,

I have add UITextView and set to KMPlaceholderTextView and set the placeholder property but whenever I run the app placeholder value can't see and getting the below warning.

Can you please help me asap?
================================================
Unknown class KMPlaceholderTextView in Interface Builder file.
Failed to set (placeholder) user defined inspected property on (UITextView): [<UITextView 0x799c5000> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key placeholder.
] Failed to set (placeholder) user defined inspected property on (UITextView): [<UITextView 0x79a17800> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key placeholder.

**Comment by danielkiedrowski** [comment]
Hello. 
I have the same problem with version 1.2.2.
What was the solution for you @Nik20112?

Thank you!
Daniel

**Comment by ranesr** [comment]
I also have the same problem with version 1.3.0.
Can you help @Nik20112 ?

Thanks.
