### ISSUE TITLE
iOS 7 auto layout exception.

### ISSUE THREAD

**Issue by kioltk** [MoZhouqi/KMPlaceholderTextView#25]
Hello, getting the exception on iOS 7.1.2 on iPhone 4, on iOS 8 and 9 everything works good.

Here is text of exception:

Fatal Exception: NSInternalInconsistencyException
Auto Layout still required after executing - layoutSubviews.
KMPlaceholderTextView's implementation of -layoutSubviews needs to call super.

**Comment by MoZhouqi** [comment]
Hi, could you give me a demo to reproduce the issue?
