### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by gabrielcandiag** [MoZhouqi/KMPlaceholderTextView#28]
Is there a branch for swift3 or any further update to make this work on Xcode 8? I'm getting this issue trying to run it:

![screen shot 2016-09-07 at 1 46 45 pm](https://cloud.githubusercontent.com/assets/10672431/18320796/b26a9706-7501-11e6-90dc-220dd2994b93.png)

**Comment by MoZhouqi** [comment]
The latest release version 1.3.0 is now supporting Swift 3.

**Comment by bitomule** [comment]
It's not published on cocoapods no?

**Comment by MoZhouqi** [comment]
`KMPlaceholderTextView 1.3.0` has been published on CocoaPods. https://github.com/CocoaPods/Specs/blob/master/Specs/KMPlaceholderTextView/1.3.0/KMPlaceholderTextView.podspec.json

**Comment by MoZhouqi** [comment]
Hi, @bitomule
`KMPlaceholderTextView 1.3.0` has been published on CocoaPods. https://github.com/CocoaPods/Specs/blob/master/Specs/KMPlaceholderTextView/1.3.0/KMPlaceholderTextView.podspec.json
