### ISSUE TITLE
Add Documentation about Swift 2.x / Swift 3 compatibility

### ISSUE THREAD

**Issue by gemmakbarlow** [MoZhouqi/KMPlaceholderTextView#29]
Hey there,

I've just updated to the latest available CocoaPod and hit some compilation issues due to not yet having upgraded to Swift 3. 

Suggest popping some notes in your `README` or release notes mentioning it.

Keep up the great work !

**Comment by MoZhouqi** [comment]
Hi @gemmakbarlow, I have updated README.md as you suggested.
