### ISSUE TITLE
Swift 3 conversion 

### ISSUE THREAD

**Issue by biogerm** [MoZhouqi/KMPlaceholderTextView#30]
Hi,

现在每次 pod update 了之后，Xcode 会提示说 KMPlaceholderTextView 没有用 Swift 3 的语法，需要convert。不知道是不是只是我的Xcode 这样？

BR
An Chin

**Comment by MoZhouqi** [comment]
Hi，试试看 CocoaPods 最新的 pre-release 版本呢？

**Comment by MoZhouqi** [comment]
把你的 CocoaPods 版本升级到 1.1.0.rc.2 就可以解决这个问题了。
