### ISSUE TITLE
It doesn't works with iOS10

### ISSUE THREAD

**Issue by GZaccaroni** [MoZhouqi/KMPlaceholderTextView#31]
In iOS10 it doesn't show anything, i can set the placeholder text and color in IB but there is no placeholder when i launch the app

**Comment by MoZhouqi** [comment]
Hi, @GZaccaroni
I have just run the example project in iOS 10 and it works, please feel free to try it by yourself.
If you have any further questions, It is better to provide a demo to reproduce the issue.

**Comment by GZaccaroni** [comment]
So i am sorry, thank you. What do you need in order to help me?
Il giorno mer 21 set 2016 alle 17:35 Zhouqi Mo <notifications@github.com>
ha scritto:

**Comment by MoZhouqi** [comment]
You could provide a demo to reproduce the issue.

**Comment by GZaccaroni** [comment]
I tried to check and no method gets called inside KMPlaceholderTextView.swift ... Now i try to add it programmatically

**Comment by GZaccaroni** [comment]
Here is the error: 

>  warning: IB Designables: Using class UITextView for object with custom class because the class KMPlaceholderTextView does not exist

**Comment by MoZhouqi** [comment]
How do you install the `KMPlaceholderTextView` library?

**Comment by GZaccaroni** [comment]
With cocoapods 1.1.0
Il giorno dom 25 set 2016 alle 16:40 Zhouqi Mo <notifications@github.com>
ha scritto:

**Comment by MoZhouqi** [comment]
Please try to set the module of the text view object to be `KMPlaceholderTextView` in the interface builder.

**Comment by GZaccaroni** [comment]
@MoZhouqi now it works... Thank you and sorry!

**Comment by MoZhouqi** [comment]
My pleasure.
