### ISSUE TITLE
Failed to render and update auto layout

### ISSUE THREAD

**Issue by tomatealbertini** [MoZhouqi/KMPlaceholderTextView#34]
file:///..../UI/Training.storyboard: error: IB Designables: Failed to render and update auto layout status for RescheduleTrainningViewController (JFO-mQ-3bH): dlopen(KMPlaceholderTextView.framework, 1): Symbol not found: __TMps13OptionSetType
  Referenced from: KMPlaceholderTextView.framework
  Expected in: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Overlays/../../../../../../Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib
 in KMPlaceholderTextView.framework

After I upgrade to XCode 8.1 (8B62) using Swift 2.3 and version 1.2.2 of KMPlaceholderTextView
appears a lot of errors like I paste above.
I use "pod 'KMPlaceholderTextView', '~> 1.2.2' ' on podfile.

All views on storyboard that uses KMPlaceholderTextView stay white on XCode.

**Comment by MoZhouqi** [comment]
Hi, @tomatealbertini 
https://github.com/CocoaPods/CocoaPods/issues/5334 This issue contains a workaround.
