### ISSUE TITLE
swift3,xcode8,I use xib to set it but failed,here is the photo,can you tell me why?

### ISSUE THREAD

**Issue by bianxiang** [MoZhouqi/KMPlaceholderTextView#35]
I want to set placeholder on top.
![tv](https://cloud.githubusercontent.com/assets/16380379/20165946/70b2b992-a74c-11e6-96dc-bd3199190503.jpg)
![tv2](https://cloud.githubusercontent.com/assets/16380379/20165947/70ba44be-a74c-11e6-8032-0da55b2667e4.png)
![tv3](https://cloud.githubusercontent.com/assets/16380379/20165948/70bbc960-a74c-11e6-8e94-53b425997590.png)

**Comment by PhiltheHen** [comment]
Hey there @bianxiang, I ran into this issue as well when using IB. I noticed the content offset was changing after loading the view. I added the following line to layoutSubviews() in the placeholder view class: 

```swift
setContentOffset(CGPoint(x: 0, y: 0), animated: false)
```

So the updated method looks like:
```swift
  open override func layoutSubviews() {
    super.layoutSubviews()
    setContentOffset(CGPoint(x: 0, y: 0), animated: false)
    placeholderLabel.preferredMaxLayoutWidth = textContainer.size.width - textContainer.lineFragmentPadding * 2.0
  }
```

I hope that helps!

**Comment by MoZhouqi** [comment]
Thanks @bianxiang @PhiltheHen, if the scroll view is the first child view of the view controller's view and the property `automaticallyAdjustsScrollViewInsets` of the view controller sets to `true` which can cause the problem.

There are two ways to solve this problem:
1. Set `automaticallyAdjustsScrollViewInsets` to `false`
2. Avoid the text view  to be the first child view of the view controller's view
