### ISSUE TITLE
Compiling has a error.

### ISSUE THREAD

**Issue by XiaoJianXiaoXu** [MoZhouqi/KMPlaceholderTextView#44]
I use the text view in storyboard named "Mine".And I have the other storyboard.
It is normal if I didn't click the Mine storyboard.
It will show a Error when I clicked Mine storyboard. It is bad.
Error info: 
Failed to render and update auto layout status for SuggestionViewController (EBX-d9-iDK): dlopen(KMPlaceholderTextView.framework, 1): no suitable image found.  Did find:
	KMPlaceholderTextView.framework: required code signature missing for 'KMPlaceholderTextView.framework'

**Comment by ElegyD** [comment]
Seems to be a issue with CocoaPods. See here: https://github.com/CocoaPods/CocoaPods/issues/7606
