### ISSUE TITLE
Swift 4.2 and Xcode 10

### ISSUE THREAD

**Issue by shoaibnomani** [MoZhouqi/KMPlaceholderTextView#50]
Can you please update this library for swift 4.2, Xcode 10 and iOS 12?

**Comment by jessecoding** [comment]
+1

**Comment by AndyLan5566** [comment]
+1

**Comment by tanakorn-dev** [comment]
Please update cocoapod too.

**Comment by kbelter** [comment]
Any news about this?
at least, add the swift_version to 4.0 so i can compile it with 4.0 with my project with 4.2 Please.

**Comment by MoZhouqi** [comment]
The version 1.4.0 has added Swift 4.2 support.

**Comment by shoaibnomani** [comment]
> The version 1.4.0 has added Swift 4.2 support.

Thank you.

**Comment by MenuHunt** [comment]
You should change the version in your documentation then, especially on the home page of the repository.
