### ISSUE TITLE
No such module KMPlaceholderTextView

### ISSUE THREAD

**Issue by OneSman7** [MoZhouqi/KMPlaceholderTextView#68]
We use your library as pod, but pulling from master branch, since pod spec was last updated 2 years ago.
Recently we started getting this error.
It seems that it is a result of moving source files to Sources folder. Podspec file was not change to accommodate this change.

**Comment by MoZhouqi** [comment]
Fixed in 12cf915155abaf9b98f2af02a7a325c699294104.
