### ISSUE TITLE
Swift 2 support

### ISSUE THREAD

**Issue by schickling** [MoZhouqi/KMPlaceholderTextView#7]
It would be nice if this library would also support swift 2. Maybe in a separate branch?

**Comment by ndmeiri** [comment]
+1

**Comment by MoZhouqi** [comment]
Thanks for all your suggestions, this branch supports for Swift 2.0 now.
https://github.com/MoZhouqi/KMPlaceholderTextView/tree/swift-2.0

**Comment by schickling** [comment]
Great! :+1:

**Comment by MoZhouqi** [comment]
Thanks, if you have any questions, please feel free to reopen the issue.
