### ISSUE TITLE
placeholder align setting

### ISSUE THREAD

**Issue by masbenx** [MoZhouqi/KMPlaceholderTextView#9]
how do i set the align mode for placeholder?

**Comment by MoZhouqi** [comment]
You can set the `textAlignment ` property.

**Comment by masbenx** [comment]
i've set the textAlignment attribute to center. the placeholder still set to left align, but the text input have set to center align
![screen shot 2015-11-09 at 11 50 00 am](https://cloud.githubusercontent.com/assets/998691/11026159/16f2c3f6-86d8-11e5-9ae6-93d3446cfde8.png)
![screen shot 2015-11-09 at 11 50 44 am](https://cloud.githubusercontent.com/assets/998691/11026162/23bb32d0-86d8-11e5-9956-0ae0aff03fbf.png)

**Comment by MoZhouqi** [comment]
Fixed in ff0be04a6e4eb230d5f0ddeec5e86800e2f254b2. Thanks for the feedback.

**Comment by MoZhouqi** [comment]
Hi, a7a17f8a79fd3f435989388b8b82c5c64e71f239 is a better way to fix the problem.
